# ========================================================
# SEGURANÇA - SMALLRYE JWT
# ========================================================
mp.jwt.verify.issuer=https://locadrive.com.br
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem