# ===================================================
# SEGURANÇA - SMALLRYE JWT
# ===================================================
mp.jwt.verify.issuer=https://locadrive.com.br
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

# ===================================================
# CONFIGURAÇÕES DO OPENAPI / SWAGGER UI
# ===================================================
mp.openapi.extensions.smallrye.info.title=LocaDrive API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API Enterprise para Gestão de Locação de Veículos
quarkus.swagger-ui.always-include=true