# ===================================================
# CONFIGURAÇÃO DE BANCO DE DADOS (POSTGRESQL / DEV SERVICES)
# ===================================================
# O Quarkus Dev Services sobe um container PostgreSQL automaticamente em modo Dev/Test
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=true

# ===================================================
# SEGURANÇA - SMALLRYE JWT
# ===================================================
mp.jwt.verify.issuer=https://locadrive.com.br
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

# ===================================================
# CONFIGURAÇÕES DO OPENAPI / SWAGGER UI
# ===================================================
mp.openapi.extensions.smallrye.info.title=LocaDrive API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API Enterprise para Gestão de Locação de Veículos
quarkus.swagger-ui.always-include=true

# ====================================================
# PERSISTÊNCIA & FLYWAY MIGRATIONS
# ====================================================
# Desativa a DDL automatica do Hibernate em favor do Flyway
quarkus.hibernate-orm.database.generation=none

# Habilita o Flyway para executar as migracoes ao iniciar a aplicacao
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1.0.0