-- Sequences exigidas pelas entidades JPA
CREATE SEQUENCE tb_cliente_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tb_veiculo_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE tb_cliente (
    id BIGINT DEFAULT nextval('tb_cliente_seq') NOT NULL,
    nome VARCHAR(250) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(250) NOT NULL UNIQUE,
    cnh VARCHAR(20) NOT NULL,
    telefone VARCHAR(20),
    CONSTRAINT pk_tb_cliente PRIMARY KEY (id)
);

CREATE TABLE tb_veiculo (
    id BIGINT DEFAULT nextval('tb_veiculo_seq') NOT NULL,
    modelo VARCHAR(100) NOT NULL,
    marca VARCHAR(100) NOT NULL,
    placa VARCHAR(10) NOT NULL UNIQUE,
    ano_fabricacao INT NOT NULL,
    valor_diaria NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    disponivel BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT pk_tb_veiculo PRIMARY KEY (id)
);

CREATE TABLE locacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_id BIGINT NOT NULL,
    veiculo_id BIGINT NOT NULL,
    data_locacao TIMESTAMP NOT NULL,
    data_fim_prevista TIMESTAMP NOT NULL, -- Alinhado com a propriedade da entidade Locacao
    data_devolucao_real TIMESTAMP,
    valor_total NUMERIC(10, 2),
    status VARCHAR(20) NOT NULL,
    CONSTRAINT pk_locacoes PRIMARY KEY (id),
    CONSTRAINT fk_locacao_cliente FOREIGN KEY (cliente_id) REFERENCES tb_cliente(id),
    CONSTRAINT fk_locacao_veiculo FOREIGN KEY (veiculo_id) REFERENCES tb_veiculo(id)
);